# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CreateIface = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.CreateIface.setGeometry(QtCore.QRect(10, 70, 281, 41))
        self.CreateIface.setObjectName("CreateIface")
        self.Connect = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.Connect.setGeometry(QtCore.QRect(20, 120, 281, 41))
        self.Connect.setObjectName("Connect")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(310, 230, 271, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CreateIface.setText(_translate("MainWindow", "Create a lwm2m interface in LO"))
        self.Connect.setText(_translate("MainWindow", "Connect lwm2m client to interface"))
        self.commandLinkButton.setText(_translate("MainWindow", "Delete lwm2m Interface in LO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
