# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import requests
import subprocess

from subprocess import check_output
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CreateIface = QtWidgets.QCommandLinkButton(self.centralwidget,clicked = lambda : self.CreateLwm2mIfaceF())
        self.CreateIface.setObjectName("CreateIface")
        self.ConnectIface = QtWidgets.QCommandLinkButton(self.centralwidget, clicked = lambda :self.ConncetToIface())        
        self.ConnectIface.setGeometry(QtCore.QRect(20, 120, 281, 41))
        self.ConnectIface.setObjectName("ConnectIface")
        self.DeleteIface = QtWidgets.QCommandLinkButton(self.centralwidget, clicked = lambda :self.DeleteIfaceF())
        self.DeleteIface.setGeometry(QtCore.QRect(310, 230, 271, 41))
        self.DeleteIface.setObjectName("DeleteIface")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CreateIface.setText(_translate("MainWindow", "Create a lwm2m interface in LO"))
        self.ConnectIface.setText(_translate("MainWindow", "Connect lwm2m client to interface"))
        self.DeleteIface.setText(_translate("MainWindow", "Delete lwm2m Interface in LO"))

    def CreateLwm2mIfaceF(self):
        
            url = "https://integ.m2m.orange.com/api/v1/deviceMgt/devices"

            payload = "{\r\n    \"id\": \"urn:lo:nsid:lwm2m:ifacelwm2m\",\r\n \"name\": \"Lwm2m device\",\r\n    \"description\": \"device for test\",\r\n    \"defaultDataStreamId\": \"urn:lo:nsid:lwm2m:ifacelwm2m\",\r\n\r\n    \"interfaces\": [\r\n        {\r\n            \"connector\": \"lwm2m\",\r\n            \"enabled\": \"true\",\r\n            \"definition\": {\r\n                \"endpointName\": \"urn:lo:lwm2m:ifacelwm2m\",\r\n                \"security\": {\r\n                    \"pskInfo\": {\r\n                        \"identity\": \"pskid\",\r\n                        \"secret\" : \"6d7973656372657470736b617a657274\"\r  \n                  }\r\n                }\r\n            }\r\n        }\r\n    ]\r\n\r\n}"
            headers = {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-API-Key': '1d576207727841a7b9aa2a1f24448f86',
                'Cookie': 'XSRF-TOKEN=d4af0d8c-5e37-415f-8c72-3da0a7f68c5c'
            }
            response = requests.request("POST", url, headers=headers, data=payload,verify =False)
            print(response.text)

    def ConncetToIface(self):
        subprocess.Popen(['powershell.exe', 'java -jar ./leshan-client-demo.jar \
                                                        -n urn:lo:lwm2m:ifacelwm2m\
                                                        -i pskid\
                                                        -p 6d7973656372657470736b617a657274\
                                                        -u lwm2m.integ.m2m.orange.com'])

    def DeleteIfaceF(self):
        url = "https://integ.m2m.orange.com/api/v1/deviceMgt/devices/urn:lo:nsid:lwm2m:ifacelwm2m"
        payload={}
        headers = {
        'X-API-Key': '1d576207727841a7b9aa2a1f24448f86'
                }

        response = requests.request("DELETE", url, headers=headers, data=payload,verify =False)

        print(response.text)
                                                     
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
